/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE 		0x40023800
#define RCC_CR   		(*(volatile uint32_t *)(RCC_BASE + 0x00))
#define RCC_CFGR		(*(volatile uint32_t *)(RCC_BASE + 0x08))

#define RCC_CR_HSEBYP (1 << 18)
#define RCC_CR_HSEON  (1 << 16)
#define RCC_CR_HSERDY (1 << 17)

#define RCC_CFGR_SW_HSE    (0x1 << 0)
#define RCC_CFGR_SWS_HSE   (0x1 << 2)


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    RCC_CR |= RCC_CR_HSEBYP;
    RCC_CR |= RCC_CR_HSEON;

    while (!(RCC_CR & RCC_CR_HSERDY));

    RCC_CFGR |= RCC_CFGR_SW_HSE;
    RCC_CFGR |= (2 << 21);
    while ((RCC_CFGR & (0x3 << 2)) != RCC_CFGR_SWS_HSE);

	for(;;);
}
